benchmark_name: gemver

executable:
  baseline: gemver_AK1_tiled_baseline.exe
  tiled: gemver_AK1_tiled.exe

source:
  baseline: gemver_AK1_tiled_baseline_fine.cu
  tiled: gemver_AK1_tiled_fine.cu

make_targets:
  baseline: gemver_AK1_tiled_baseline.exe
  tiled: gemver_AK1_tiled.exe

parameters:
  shifts: [1,4,8,12,16,20,24,28,32,36,40,44,48,52,56,60,64] #[5, 6, 8, 10, 12, 13]
  num_tiles: [1, 2, 4, 8, 16, 32]
  repeats: 100
  threads_per_block: 256
  verify: true
  debug: true 
  measure_end2end: true
  
output_csv: results_gemver.csv