benchmark_name: gemver

executable:
  baseline: gemver_AK1_tiled_baseline.exe
  tiled: gemver_AK1_tiled.exe

source:
  baseline: gemver_AK1_tiled_baseline_fine.cu
  tiled: gemver_AK1_tiled_fine.cu

make_targets:
  baseline: gemver_AK1_tiled_baseline.exe
  tiled: gemver_AK1_tiled.exe

parameters:
  shifts: [16,24,32,40,48,56,64,72,80,88,96,104,112,120,128] #[5, 6, 8, 10, 12, 13]
  num_tiles: [1, 2, 4, 8, 16, 32]
  repeats: 100
  threads_per_block: 256
  verify: true
  debug: true 
  measure_end2end: true
  
output_csv: results_gemver.csv